export const FETCH = 'fetch'
export const CONFIG = 'config'
export const SHOW_INFORMATION_MESSAGE  = 'showInformationMessage'
export const SET_TOC = 'setTOC'
export const DO_COPY = 'doCopy'
export const DO_TRANSLATE = 'doTranslate'
export const CONTENTS = 'contents'
export const GET_CONTENT = 'getContent'